### PR TITLE
Fixes #35: line endings for mac/unix systems

### LINKED ISSUE #35: env: node\r: No such file or directory
Running OSX 10.10.2 Yosemite. Installed Manifold with:

*npm install -g ManifoldJS*

In terminal I try to run:

*manifoldjs www.http://meteorite.azurewebsites.net*
 and I receive:

*DaveVoyless-MacBook-Pro:~ DaveVoyles$ manifoldjs http://meteorite.azurewebsites.net
env: node\r: No such file or directory*

What do you think the issue could be?

### PR DESCRIPTION
**Pull request by kevincobain2000**
**Install and get the location**

```
05/04/15 @ 1:27PM - kevincobain2000@Mac Air ~/Downloads npm install -g manifoldjs
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":"0.10.36","npm":"2.5.0"})
/usr/local/bin/manifoldjs -> /usr/local/lib/node_modules/manifoldjs/manifoldjs.js
..
...
..
```

The Issue #35

```
05/04/15 @ 1:28PM - kevincobain2000@Mac Air ~/Downloads rm -rf native;manifoldjs http://localhost:8080/ -d native  -p ios -b
env: node\r: No such file or directory
```

Work Log

```
05/04/15 @ 1:29PM - kevincobain2000@Mac Air ~/Downloads ls -la /usr/local/bin/manifoldjs
lrwxr-xr-x  1 kevincobain2000  admin  44 May  4 13:28 /usr/local/bin/manifoldjs -> ../lib/node_modules/manifoldjs/manifoldjs.js
```

```
05/04/15 @ 1:30PM - kevincobain2000@Mac Air ~/Downloads ls -l /usr/local/lib/node_modules/manifoldjs/manifoldjs.js
-rwxr-xr-x  1 kevincobain2000  wheel  6018 Apr 30 00:22 /usr/local/lib/node_modules/manifoldjs/manifoldjs.js
05/04/15 @ 1:31PM - kevincobain2000@Mac Air ~/Downloads wc -l /usr/local/lib/node_modules/manifoldjs/manifoldjs.js
     171 /usr/local/lib/node_modules/manifoldjs/manifoldjs.js
```

```
 05/04/15 @ 1:31PM - kevincobain2000@Mac Air ~/Downloads cat /usr/local/lib/node_modules/manifoldjs/manifoldjs.js |col -b > temp; cp temp /usr/local/lib/node_modules/manifoldjs/manifoldjs.js
 05/04/15 @ 1:32PM - kevincobain2000@Mac Air ~/Downloads wc -l /usr/local/lib/node_modules/manifoldjs/manifoldjs.js
     171 /usr/local/lib/node_modules/manifoldjs/manifoldjs.js
```

----

**This Pull Request**

```
05/04/15 @ 1:38PM - kevincobain2000@Mac Air ~/Downloads cp /usr/local/lib/node_modules/manifoldjs/manifoldjs.js ManifoldJS/manifoldjs.js
```

**All Good**

```
05/04/15 @ 1:32PM - kevincobain2000@Mac Air ~/Downloads rm -rf native;manifoldjs http://localhost:8080/ -d native  -p ios -b
WARNING: No manifest found. A new manifest will be created.Validation warning (ios): An app icon of the following sizes is required: 76x76, 120x120, 152x152 and 180x180Validation warning (ios): An 1024x1024 app icon for the App Store is required
Validation warning (ios): A launch image of the following sizes is required: 750x1334, 1334x750, 1242x2208, 2208x1242, 640x1136, 640x960, 1536x2048, 2048x1536, 768x1024 and 1024x768
ERROR: Failed to copy the manifest to the app folder.
WARNING: The Cordova project could not be created successfully.
WARNING: One or more errors occurred when generating the application.
```

**After Merge**

Actual diff is here (https://github.com/manifoldjs/ManifoldJS/pull/36/files#diff-b3753cf36ac588be23849590db6a56bcR1), it is invisible but it is a replacement of new line character \r for unix/mac systems. New line chars don't create a diff so I had to add a new line here (https://github.com/manifoldjs/ManifoldJS/pull/36/files#diff-b3753cf36ac588be23849590db6a56bcR3) to generate atleast some diff. After Merging this you can get rid of that new line or leave it as it is.

### CODE REVIEW

**Comment by DaveVoyles** [comment]
OK, I see now. This is the same issue I was having before, too. 

So once this is pulled, it should resolve the issue and terminal will be able to locate the ManifoldJS folder on the machine, correct?

**Comment by nickdesaulniers** [comment]
bump

**Comment by nbellocam** [comment]
Sorry, but I couldn't find what you fixed with this pull request. I can't find the wrong EOL in the master branch. However, I found the issue when installed the tool from npm. It seems to be an issue with the publication of the module (note that you may need to clean your npm cache).

Are you seeing this issue when installing from github directly? (you can use `npm install -g manifoldjs/manifoldjs`).

**Comment by kevincobain2000** [comment]
@nbellocam ah sorry, master is good (no wrong EOL there) & (no need to merge this pull request). I should have checked more thoroughly !
Most likely the wrong line ending char still resides in the publication module (eb2b9d15caab7c908d6b71205901a6878781654f) .

**Pull request closed without merging**
